### ISSUE TITLE
event status

### ISSUE THREAD

**Issue by sherpadawan** [pikim/grav-plugin-events#15]
is it possible to add an event status (scheduled, postponed, canceled)
Thanks in advance

**Comment by pikim** [comment]
Finally I merged your code. Could you please do some testing as I don't use this feature?

**Comment by sherpadawan** [comment]
I already did, I use it on my websites,
default status is none
I thing there is work to do to merge your plugin and the fullcalendar one. https://github.com/wernerjoss/grav-plugin-fullcalendar
I forked it but we need more work on it to achieve rrule import with ics files (local or remote)
and it would really great there would be a sync between remote info and  events plugin.
What do you think about it?
