### ISSUE TITLE
Can not read ICS file

### ISSUE THREAD

**Issue by ironbrunet** [pikim/grav-plugin-events#17]
Have added the ics file to the ical folder but cannot seem to read the file - any help appreciated

**Comment by sherpadawan** [comment]
the fullcalendar plugin sherpadawan/grav-plugin-fullcalendar or the original repo in branch fc5 supports ics remote or locla ics import. But it does not import it as event.
Some merging work between those two plugins would be interesting to do.

**Comment by pikim** [comment]
You don't store the ics file in the ical folder. The plugin will parse the ics file and store the found events in that folder. You have to store the ics file anywhere else and provide a path to it.

**Comment by sherpadawan** [comment]
I think it is easier to provide ics files as uploaded files on page backoffice editor. 
As a server side dir  is accessible anyway which may be sync with something else.
esaier to manage shortcodes, and other way of using ics files programmatically in the UI.

**Comment by pikim** [comment]
Is this still an issue? It works on my setup.

**Comment by pikim** [comment]
I just extended the readme accordingly and added an example screenshot.
