### ISSUE TITLE
French days and months should be all lowercase

### ISSUE THREAD

**Issue by berthelemy** [pikim/grav-plugin-events#20]
Hi there,
Currently, when I set the default site language to French, the days and months display the correct French words. But the first letter is capitalised. In French, days and months do not have a first capital letter.

I've been trying to see how this is set within the Events plugin, but have got a bit lost in the code. Can you help?

Thanks,
Mark

**Comment by pikim** [comment]
Hi,
sorry for the delayed answer. Translation takes the values from Grav itself, so fixing the names there should help. In your case it would be in system/languages/fr.yaml, see https://github.com/getgrav/grav/blob/fdf884036da0c3b613be75e815eaebb6de015722/system/languages/fr.yaml. You can try this on your instance and report how it worked.
Best regards,
Michael

**Comment by berthelemy** [comment]
Sorry for the delay at my end. This is all working fine now.
