### ISSUE TITLE
Merging work with grav-plugin-fullcalendar would be  very  intereting.

### ISSUE THREAD

**Issue by sherpadawan** [pikim/grav-plugin-events#21]
I forked the original grav-plugin-fullcalendar plugin. 
And I would like to lake a single plugin with fullcalendar whihc reads ics files as:
- remote url
- local media page files
There is a work to do on how to merge those work.
 I don't really know how for now.
But we should work together !

**Comment by pikim** [comment]
I don't understand what you try to achieve. Could you please elaborate?

**Comment by sherpadawan** [comment]
I meant ics files can be remote one as well as page uploaded files (not included by means of shortcode)
This is an old comment ...
