### ISSUE TITLE
can i create bilingual events?

### ISSUE THREAD

**Issue by kostaskleas** [pikim/grav-plugin-events#22]
i am trying to build a bilingual web site for a private school and all i want to do is create an event for both languages, but what happens is that when i switch into greek the same evnt appears written both in greek and in english...

**Comment by pikim** [comment]
How do you separate languages in the ics file?

**Comment by pikim** [comment]
You'll have to create one file for each language, e.g. `event.de.md` and `event.en.md`. I just tested it and it works.
One of the next releases will also support multi-language ics files.
