### ISSUE TITLE
|raw filter required in event_item.html.twig

### ISSUE THREAD

**Issue by maxroseGIT** [pikim/grav-plugin-events#26]
Hi, thanks for the nice plugin.

I run into html-tags being displayed in the "events"-list and "event"-items. (I use Grav v1.7.14 - Admin v1.10.14)

I figured that this can be solved by using the `|raw`-filter on `page.content `and `page.summary` in the `event_item.html.twig` template file on `lines 39 and 47`.

However, in `line 17` there is a `&ndash;` symbol that I don't know how to filter in order to have it rendered properly by the browser. Any idea how to solve this?

**Comment by maxroseGIT** [comment]
Is also found a missing `|raw`-filter for `event.summary(50)` in file `event_calendar_item.html.twig` on `line 14`.

**Comment by therealgorgan** [comment]
Thanks for posting this, I also run into that issue and will resolve it like you mentioned. Good one!

**Comment by therealgorgan** [comment]
@maxroseGIT btw I also had the &ndash; appearing, this is how I solved it: 
![image](https://user-images.githubusercontent.com/33201476/118227865-e2c5e180-b44e-11eb-873c-9854397a3f09.png)

**Comment by pikim** [comment]
Could you please manually install the latest version from the zip file and give me some feedback if I properly implemented your changes?
