### ISSUE TITLE
Event blueprint

### ISSUE THREAD

**Issue by sherpadawan** [pikim/grav-plugin-events#29]
Those lines are duplicated in the blueprint file 

 header.event.status-section:
              type: section
              underline: true
              title: Status
            header.event.status:
              label: Status
              type: select
              default: "scheduled"
              options:
                "": "None"
                "scheduled": "scheduled"
                "postponed": "postponed"
                "cancelled": "cancelled"
              title: Status
              help: Possible values are scheduled, postponed, cancelled.

**Comment by pikim** [comment]
Thanks for the feedback. I never use the blueprints so I couldn't notice.
Fixed in https://github.com/pikim/grav-plugin-events/commit/7f1a2046a71ee104cdac26e2749c2a7c962c1d10
