### ISSUE TITLE
NO geoloc API KEY

### ISSUE THREAD

**Issue by sherpadawan** [pikim/grav-plugin-events#4]
Hello, as there is no google maps api key in plugin configuration, or any use of a google maps plugin dep, I get this :
Array ( [error_message] => You must use an API key to authenticate each request to Google Maps Platform APIs. For additional information, please refer to http://g.co/dev/maps-no-account [results] => Array ( ) [status] => REQUEST_DENIED )

**Comment by pikim** [comment]
To be honest I never used that feature. Could you please write down the steps to reproduce the issue? What does the event look like, what theme are you using?

**Comment by pikim** [comment]
@sherpadawan, could you please test the new release? Now geocoding can be disabled and an API key can be defined.

**Comment by sherpadawan** [comment]
Hello,
I installed the latest version.
Why have you choosen to depend on the Quark theme ? I makes the plugin not ready to use with custom theme... You should provide a partial/base template .
There is a notice for undelcared count var in /user/plugins/events/classes/eventsProcessor.php at line 484 ... makes crash on development platform)
Thanks for your work anyway

**Comment by pikim** [comment]
> Why have you choosen to depend on the Quark theme ?

You'll have to ask the initial author, but I assume you won't get an answer as he seems to have moved on. Could you point me to an example that shows what you mean?

> There is a notice for undelcared count var in /user/plugins/events/classes/eventsProcessor.php at line 484 ... makes crash on development platform)

I'll add a default clause which sets $count to 0.

**Comment by sherpadawan** [comment]
Ok i created a new issue to solve the template dependencie issue see #7
