### ISSUE TITLE
No icalendar folder is being created upon saving in settings.

### ISSUE THREAD

**Issue by TheLexoPlexx** [pikim/grav-plugin-events#6]
- Grav: 1.6.21 (latest)
- Plugin: 1.1.14 (latest)

Just installed the events plugin into Grav using the Admin-Backend. No folder is being created, no matter the name of the folder.
Tried running XAMPP as admin in case of read/write-errors, no success.

**Comment by pikim** [comment]
The folder will be created when you save the admin settings. Did you do that?
I can't reproduce your issue although we're using the same revisions.

**Comment by TheLexoPlexx** [comment]
I just used a fresh install of grav and everything works fine there, except the ical-files are deleted from the generated folder, I'll have to figure that out later. But it seems to be a problem on my end.

**Comment by TheLexoPlexx** [comment]
Painfully embarrassing issue: The plugin was deactivated for some reason which I only noticed when deactivating other plugins.
