### ISSUE TITLE
Error using repeating events with PHP7.3 in calendar view

### ISSUE THREAD

**Issue by slowfox089** [pikim/grav-plugin-events#8]
When showing the calendar page with php 7.3 and repeating events there are some errors in eventsProcessor.php

1) $count is not defined:
solved by adding 'global $count;' to function calculateCount
2) $newStart, $newEnd not defined:
solved by adding 'global $newStart, $newEnd;' to function calculateNewDates

**Comment by pikim** [comment]
Could you please try the following file? Change the extension to php and replace the original version.
[eventsProcessor.txt](https://github.com/pikim/grav-plugin-events/files/4251650/eventsProcessor.txt)

**Comment by slowfox089** [comment]
Hi Pikim,
don't know what exactly you've done :-) But it seems this version of the eventsProcessor did the trick. Even I wasn't able to spot a difference in the functions that did throw the error :-)

But I didn't have the time to check the complete file ;-)

Thanks and I hope the bugfix is soon available, so I don't have to update manually ;-)

Greetings
