### ISSUE TITLE
Show the event location

### ISSUE THREAD

**Issue by git-rebug** [pikim/grav-plugin-events#9]
I'd appreciate if the location details were displayed and I'd be happy to make a PR.

How would you expect such a feature to behave? I assume it should be possible to turn it off and on. For me, the simple display of text is sufficient, but I do think that it might be interesting to link addresses and GPS coordinates to online maps.
Particularly if the latter is desired, I ask everyone involved for help, gladly with my support even in a later step that's following the first implementation!

**Comment by pikim** [comment]
For me, the location as text would also be sufficient. Offering addresses/GPS coordinates on maps would make it more versatile. But to be honest at the moment I need neither of the two.

**Comment by pikim** [comment]
Finally I merged your code. Could you please do some testing as I don't use this feature?
